### ISSUE TITLE
NavigationSystem and NavigationPath missing

### ISSUE THREAD

**Issue by Mykybo** [tomlooman/CoopHordeShooter#1]
In `STrackerBot.cpp` you include NavigationSystem and NavigationPath:

```
#include "AI/Navigation/NavigationSystem.h"
#include "AI/Navigation/NavigationPath.h"
```

but they are not in the repo, am I missing something?

**Comment by wisien92** [comment]
These files are engine files (and I can't see them in repo). Are you using 4.20-preview? I had the same issue. Rolling back to 4.19.2 (and rebuilding sollution) fixed that for me.

**Comment by Mykybo** [comment]
yeah, I am using 4.20, I just removed that section of code, would have to update to 4.20 eventually anyways

**Comment by wisien92** [comment]
That's true. I like to wait till comunity prepares transition guide :)

**Comment by Chosker** [comment]
got the same issue, resolved it quickly

in STrackerBot.cpp change 
`#include "AI/Navigation/NavigationSystem.h"`
for
`#include "NavigationSystem/Public/NavigationSystem.h"`

in STrackerBot.cpp change
`#include "AI/Navigation/NavigationPath.h"`
for
`#include "NavigationSystem/Public/NavigationPath.h"`

in CoopGame.Build.cs change
`PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore" });`
for
`PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "NavigationSystem" });`


compile and enjoy :)

**Comment by tomlooman** [comment]
Thanks for the solutions guys, I've went ahead and created new Branches for the engine versions including 4.20 to support the API changes like the AI module change.

**Comment by acdc4567** [comment]
Everything up to this point is all right..Change UNavigationSystem::FindPathToActorSynch... to UNavigationSystemV1::FindPathToActorSynch...
