### ISSUE TITLE
Upgrading it to UE4.26

### ISSUE THREAD

**Issue by Ramstein** [tomlooman/CoopHordeShooter#10]
First, I had an issue with UCameraShake, fixed it with UCameraShakeBase.

Now, still, I have a lot of issues in SWeapon.CPP

code - LNK2019
Description- unresolved external symbol "__declspec(dllimport) public: static enum EPhysicalSurface __cdecl UPhysicalMaterial::DetermineSurfaceType(class UPhysicalMaterial const *)" (__imp_?DetermineSurfaceType@UPhysicalMaterial@@SA?AW4EPhysicalSurface@@PEBV1@@Z) referenced in function "protected: void __cdecl ASWeapon::Fire(void)" (?Fire@ASWeapon@@IEAAXXZ)	
file - C:\Users\Administrator\Downloads\CoopHordeShoote\Intermediate\ProjectFiles\SWeapon.cpp.obj

**Comment by tomlooman** [comment]
Upgraded the project to 4.26 now including any deprecation warning fixes.

Your issue was that "PhysicsCore" must be added to .build.cs for 4.26
